@baseUrl = http://localhost:3000
@token = """
@adminToken = ""

### Test home page
GET {{baseUrl}}/

########### AUTHENTICATIE & AUTORISATIE

### Registreren 
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "username": "Joussef3",
    "email": "joussef3@student.vives.be",
    "password": "Azerty123"
}

### Inloggen 
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "joussef@student.vives.be",
    "password": "Azerty123"
}

###

########### SKINS

### GET alle skins 
GET {{baseUrl}}/api/skins

### Nieuwe skin toevoegen (alleen admin)
POST {{baseUrl}}/api/skins
Content-Type: application/json
x-auth-token: {{adminToken}}

{
    "name": "Glacier",
    "weaponType": "MP7",
    "rarity": "Epic",
    "releaseSeason": "Operation Black Ice"
}

###

########### GEBRUIKERS & MARKTPLAATS

### GET alle gebruikers (alleen admin)
GET {{baseUrl}}/api/users
x-auth-token: {{adminToken}}

### Nieuwe gebruiker toevoegen (alleen admin)
POST {{baseUrl}}/api/users
Content-Type: application/json
x-auth-token: {{adminToken}}

{
    "username": "NieuweUser",
    "email": "nieuwe.user@student.vives.be",
    "password": "Azerty123",
    "credits": 120
}

### GET alle advertenties
GET {{baseUrl}}/api/listings

### Skin te koop zetten 
POST {{baseUrl}}/api/listings
Content-Type: application/json
x-auth-token: {{token}}

{
    "price": 350,
    "skinData": {
        "name": "Glacier",
        "weaponType": "Assault Rifle",
        "rarity": "Epic",
        "releaseSeason": "Operation Black Ice"
    }
}
