### Test home page
GET http://localhost:3000/
###

### GET alle skins 
GET http://localhost:3000/api/skins

###

### nieuwe skin toevoegen
POST http://localhost:3000/api/skins
Content-Type: application/json

{
    "name": "Glacier",
    "weaponType": "MP7",
    "rarity": "Epic",
    "releaseSeason": "Operation Black Ice"
}

### POST met ongeldige data
POST http://localhost:3000/api/skins    
Content-Type: application/json

{
    "name": "Glacier",
    "weaponType": "MP7",
    "rarity": "Exotic",
    "releaseSeason": "Operation Black Ice"
}

### GET alle gebruikers
GET http://localhost:3000/api/users

### nieuwe gebruiker toevoegen
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "Joussef",
    "email": "joussef.boulbane@student.vives.be"
}